### ISSUE TITLE
dependency not found

### ISSUE THREAD

**Issue by miaojiuchen** [lao-siji/lao-siji#1]
github.com/cnt0/gotrntmetainfoparser
this package seems to has been deleted

**Comment by rixtox** [comment]
Got it. I will write a simple info hash parser recently.

**Comment by miaojiuchen** [comment]
![image](https://cloud.githubusercontent.com/assets/9482138/24346050/5d8df69a-1305-11e7-8eed-4745d0ea56c4.png)

**Comment by rixtox** [comment]
Hot fixed. Please check if working.
